### ISSUE TITLE
The "History" is not agreed: empty the document and abandon the effort

### ISSUE THREAD

**Issue by chaals** [w3c/AB-public#130] opened 2023-09-28 06:49 UTC
The history document isn't a particularly accurate recounting of the facts, and is less likely to reach consensus on points of contention. What is there right now is (at least IMHO, and I was there for a lot of it) misleading, and complicates the effort to reach a consensus.

Writing history is a complex task, and probably not one that W3C's community is well-suited to doing.

Leaving a contentious History out there seems like a bad way to generate goodwill.

I propose we withdraw the document.

**Comment by frivoal** [comment] 2023-09-28 07:02
I think this can be considered a duplicate of https://github.com/w3c/AB-public/issues/105, arguing for option 2 or or maybe 4 in there.

**Comment by chaals** [comment] 2023-09-28 07:10
Not quite. I contend that the AB is doing harm to W3C by maintaining the document in place without addressing the issue, and that an issue framed as "Publish [that content]" isn't helpful.

**Comment by frivoal** [comment] 2023-09-28 07:37
The title isn't "Publish X", which might suggest that we should publish it, but "Publication of X", which questions whether we should (and if so, how). I think you're saying that we should not. I am not sure why "we should not publish this" is a separate question from "what should we do with this?" It feels like an answer to me.

Either way, I am OK with deleting the source in Github, and just have this rest at the dated URL where it already is, and not perpetuate it any further.

**Comment by frivoal** [comment] 2023-09-28 14:46
#105 and #131 have been resolved, so the status of the History on TR is solved. The remaining question is what to do about https://github.com/w3c/AB-public/tree/main/Vision/History.bs

I think we should `git rm` it. Github is not where we publish things for public consumption, and it is not appropriate to use GitHub as a place where we point people to documents they should read (c.f. https://www.w3.org/2023/Process-20230612/#report-stability). GitHub is where we work on stuff. We're not working on this stuff. We should remove it. Leaving it there suggests that it is an active work item, would invite people to file issues about it, call for us to respond to them… None of that is useful.

GitHub preserves history, so that's available for anyone who needs it. But we don't need an Editor's Draft for something that has no Editor and isn't the draft of anything.

**Comment by dwsinger** [comment] 2023-09-28 15:07
Characterizing other people's work as "bunk" is inappropriate. Please consider renaming this issue. 

The history had an initial purpose which is probably past; to provide some context for members who did not live it. No doubt it's wrong and misleading in various ways, and maybe no-one needs context any more.

**Comment by cwilso** [comment] 2023-09-28 17:21
On discussion: the issue here seems to revolve around whether we clearly identify that the legacy remnant in a dated copy of the document is not believed to be accurate

**Comment by frivoal** [comment] 2023-09-29 02:11
If a warning of some sort is needed about something published on TR, the warning should be on TR. As far as I am concerned, the note at the beginning of https://www.w3.org/TR/2023/DNOTE-w3c-vision-20230725/#history, combined with the fact that as per #105 the History section will no longer be included or referenced in subsequent publications, is adequate, and nothing more is needed. Per the Process publication of material as a Draft Note (or even as Note) does not imply consensus over the content of the document (which we don't seem to have), merely that we had group consensus to publish it (which we did).

Even then, if we did think that stronger disclaimers were needed, I don't think GitHub would be an appropriate place to store them.

**Comment by michaelchampion** [comment] 2023-10-02 01:54
Just for the record, since the document in question is going down the [memory hole](https://en.wikipedia.org/wiki/Memory_hole) , the original intent wasn't to write a "history of W3C."  It was to frame what became the Vision work as a pivot in W3C's mission to face the challenges the web created.

This was our narrative: The original mission really WAS "lead the web to its full. potential", with Tim, the team, academic experts, and industry inventing all sorts of stuff, some of which became the Web Platform.  In hindsight, that mission de-facto morphed into making the existing web work better in the first years of this century. The best example is CSS 2.0, conceived in an era of rapid invention and experimentation, but wasn't  very interoperable.  It  took more than 10 years to standardize CSS 2.1 with the help of literally thousands of interoperability tests.  By the time the Vision work started in 2020, the web platform was highly interoperable and W3C's culture had evolved to strongly encourage incubation before standardization, and proven interoperability to get to Recommendation.  But while the web had proven its original potential and become a vital part of human communication, a LOT of problems had become apparent.  It was time to "pivot to integrity" (as the Vision doc was once subtitled) and re-focus W3C's mission on making the web safer for users.

Sure, one can poke lots of holes in that as a "history of W3C."  It wasn't intended to be.  It was **explicitly** opinionated -- let's stop pretending the Web is a pure benefit to humanity; Let's give the first generation of W3Cers lots of credit for inventing the web platform, lots of respect to the 2nd generation who did the hard tedious work of getting (most features of most) W3C specs interoperating in the real world, but a new Vision is needed to "lead the web to its full potential" going forward.  Of course that narrative will not get broad consensus, it was intended to CHALLENGE the status quo, replacing a somewhat a techno-centric mission.  with a values-driven mission.  

That said, I am comfortable with the CG decision on what to do with the document.  There appears to be a rough consensus in the group on a vision of W3C as values-driven and sensitive to the damage the web can cause, whether or not the previous vision was as techno-utopian as the "history" document portrayed it.

**Comment by chaals** [comment] 2023-10-02 16:19
> the original intent wasn't to write a "history of W3C."

In that case, I suggest it was a bad idea to put it in a TR draft where it appears to be an effort to describe "the History of W3C", and we should think about how we avoid that happening again.

**Comment by cwilso** [comment] 2023-10-20 17:31
Fixed by https://github.com/w3c/AB-public/pull/132.

**Closed by cwilso** 2023-10-20 17:31 UTC
Labels: Vision
